(("default" . ((user-emacs-directory . "~/.local/share/emacsen/emacs.d" )
                  (server-name . "vanilla")
                  (straight-p . t)))
    ("doom" . ((user-emacs-directory . "~/.local/share/emacsen/doom")
                  (custom-file . "~/.config/emacsen/doom/custom.el")
                  (server-name . "doom")
                  (env . (("DOOMDIR" . "~/.config/emacsen/doom")
                             ("DOOMLOCALDIR" . "~/.cache/emacsen/doom")))
                  (straight-p . nil)))
    ("prelude" . ((user-emacs-directory . "~/.local/share/emacsen/prelude")
                     (server-name . "prelude")
                     (env . (("PRELUDE_CONFIG_HOME" . "~/.config/emacsen/prelude")))
                     (straight-p . nil)))
    ("centaur" . ((user-emacs-directory . "~/.local/share/emacsen/centaur")
                     (server-name . "centaur")))
    ("spacemacs" . ((user-emacs-directory . "~/.local/share/emacsen/spacemacs")
                       (server-name . "spacemacs"))))
